### ISSUE TITLE
[Insight] The composer.json file should not raise warnings - in composer.json, line 0

### ISSUE THREAD

**Issue by CyberSecutor** [HylianShield/validator#17]
**[in composer.json](https://github.com/HylianShield/validator/blob/a68ac642005b09c1dff0b7f7733409a89c577ba5/composer.json#L0)**

> The version field is present, it is recommended to leave it out if the package is published on Packagist.

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/63a12b6e-3e9e-4ccf-bba0-7cde18ce9923/analyses/1)_

**Comment by johmanx10** [comment]
This issue has been fixed in an earlier version of the validator
